# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Rcc method implementation for knapsack dynamic programming
#' 
#' @param MaxWeight numeric vector indicating maximum capacity of knapsack
#' @param weights numeric vector indicating weight of individual element in the datase
#' @param value value of individual element in the dataset
#' @param length number of objects in the data set
#' @return a matrix with sequence of all weights and values.
#' @export
knapSackdynamic_cpp <- function(MaxWeight, weights, value, length) {
    .Call(`_knapsack_knapSackdynamic_cpp`, MaxWeight, weights, value, length)
}

rcpp_hello_world <- function() {
    .Call(`_knapsack_rcpp_hello_world`)
}

